# Gitleaks secrets scan

name: Gitleak Secrets Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install golang
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          sudo apt install golang-go
      - name: Install gitleaks
        run: |
          sudo apt install gitleaks

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          #!/bin/bash
          ## Ensure git credentials are set beforehand
          # Run gitleaks
          echo "[+] Running gitleaks..."
          cd ${{ github.workspace }}
          if ! gitleaks detect -v | tee gitleaks-report.txt; then
              echo "[-] Failed to run gitleaks scan"
              exit 1
          fi
          echo "[+] Gitleaks scan complete"
          
          echo "[+] Secrets scan saved to gitleaks-report.txt"
      - name: Upload report artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: ${{ github.workspace }}/gitleaks-report.txt
